apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  namespace: performance
  labels:
    jmeter_mode: slave
spec:
  clusterIP: None  # headless service
  ports:
    - port: 1099
      name: jmeter
      targetPort: 1099
    - port: 50000
      name: rmi
      targetPort: 50000
    - port: 4445
      name: stoptest
      targetPort: 4445
  selector:
    jmeter_mode: slave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  namespace: performance
  labels:
    jmeter_mode: slave
spec:
  replicas: 1  # можеш змінити кількість слейвів
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: jmslave
        image: youketero/jmeter:k8s
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "SLAVE"
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && until [ -f /opt/jmeter/load_test ]; do sleep 5; done && /bin/bash /opt/jmeter/load_test"]
        ports:
        - containerPort: 1099
        - containerPort: 50000
        - containerPort: 4445
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"
        livenessProbe:
          exec:
            command: ["pgrep", "-f", "jmeter"]
          initialDelaySeconds: 10
          periodSeconds: 10
