apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmeter-data-dir-pvc
  namespace: performance
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
  namespace: performance
  labels:
    app: jmeter
    jmeter_mode: master
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: jmeter
        jmeter_mode: master
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
      - name: jmmaster
        image: youketero/jmeter:k8s
        imagePullPolicy: Always
        volumeMounts:
          - name: jmeter-logs
            mountPath: /jmeter
          - name: jmeter-data-dir
            mountPath: /report
        env:
        - name: MODE
          value: "MASTER"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && until [ -f /opt/jmeter/load_test ]; do sleep 5; done && /bin/bash /opt/jmeter/load_test"]
        ports:
        - containerPort: 60000   # RMI для зв’язку зі slave
        - containerPort: 1099    # RMI registry (часто потрібен)
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "2048Mi"
            cpu: "1024m"
        livenessProbe:
          exec:
            command: ["pgrep", "-f", "jmeter"]
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Never
      volumes:
        - name: jmeter-logs
          persistentVolumeClaim:
            claimName: jmeter-logs-pvc
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: jmeter-data-dir-pvc
# JMeter Deployment
# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: jmeter-deployment
  # namespace: performance
# spec:
  # replicas: 1
  # selector:
    # matchLabels:
      # app: jmeter
  # template:
    # metadata:
      # labels:
        # app: jmeter
    # spec:                 # <--- volumes повинні бути тут
      # containers:
      # - name: jmeter
        # image: youketero/jmeter:k8s
        # env:
          # - name: JMX_FILE
            # value: "my-test.jmx"
        # args: ["-n", "-t", "/jmeter/${JMX_FILE}"]
        # volumeMounts:
          # - name: jmeter-logs
            # mountPath: /jmeter
      # volumes:
        # - name: jmeter-logs
          # persistentVolumeClaim:
            # claimName: jmeter-logs-pvc
