# apiVersion: apps/v1
# kind: Deployment
# metadata:
  # name: jmeter-deployment
  # namespace: performance
# spec:
  # replicas: 1
  # selector:
    # matchLabels:
      # app: jmeter
  # template:
    # metadata:
      # labels:
        # app: jmeter
    # spec:
      # containers:
      # - name: jmeter
        # image: youketero/jmeter:k8s
        # volumeMounts:
        # - name: jmeter-volume
          # mountPath: /jmeter
      # volumes:
      # - name: jmeter-volume
        # hostPath:
          # path: /opt/
          # type: Directory
      # restartPolicy: Always
      
# JMeter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-deployment
  namespace: performance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:                 # <--- volumes повинні бути тут
      containers:
      - name: jmeter
        image: youketero/jmeter:k8s
        env:
          - name: JMX_FILE
            value: "my-test.jmx"
        args: ["-n", "-t", "/jmeter/${JMX_FILE}"]
        volumeMounts:
          - name: jmeter-logs
            mountPath: /jmeter
      volumes:
        - name: jmeter-logs
          persistentVolumeClaim:
            claimName: jmeter-logs-pvc
