# Deployment for kibana service
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: performance
spec:
  version: 8.13.4
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      spec:
        type: NodePort       # Service for accessing kibanan from the browser
        ports:
          - port: 5601
            nodePort: 32343 
