---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: performance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: performance
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat
  namespace: performance
spec:
  type: metricbeat
  version: 8.13.4
  config:
    metricbeat.modules:
      - module: system
        period: 10s
        metricsets:
          - cpu
          - memory
          - network
          - filesystem
          - process_summary
        processes: ['.*']

    output.logstash:
      hosts: ["logstash-sample-ls-beats:5044"]

  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        containers:
          - name: metricbeat
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: proc
                mountPath: /hostfs/proc
                readOnly: true
              - name: cgroup
                mountPath: /hostfs/sys/fs/cgroup
                readOnly: true
        volumes:
          - name: proc
            hostPath:
              path: /proc
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup