"""add new field

Revision ID: 341a7ba97576
Revises: db3182658a4c
Create Date: 2021-04-04 22:29:52.789282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341a7ba97576'
down_revision = 'db3182658a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
